version: "3.3"
services:
  db:
   image: influxdb:1.5
   volumes:
      - ./data:/var/lib/influxdb
   ports:
      - "8083:8083"
      - "8089:8089/udp"
      - "8086:8086"
   environment:
      - INFLUXDB_DB=test_mindx
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_UDP_DATABASE=test_mindx
      - INFLUXDB_UDP_BIND_ADDRESS=:8089
