version: "3.3"
services:
  processor:
    image: processor:latest
    ports:
      - "5001:5001"
    links:
      - db
    depends_on:
      - db
  generator:
    image: generator:latest
    depends_on:
      - processor
    links:
      - processor
  db:
   image: influxdb:1.5
   volumes:
      - ./data:/var/lib/influxdb
   ports:
      - "8083:8083"
      - "8089:8089/udp"
      - "8086:8086"
   environment:
      - INFLUXDB_DB=mindx
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_UDP_DATABASE=mindx
      - INFLUXDB_UDP_BIND_ADDRESS=:8089
